(package "satysfi-ts-mode"
         "0.1.0"
         "A tree-sitter based major-mode for SATySFi")

(website-url "https://github.com/Kyure-A/satysfi-ts-mode")
(keywords "languages")

(package-file "satysfi-ts-mode.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "29.1")

(development
 (depends-on "elsa")
 (depends-on "elisp-lint"))
